import { YerlesimYeri } from './types';

export const yerlesimVerileri: YerlesimYeri[] = [
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "2000 EVLER Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "AHMET REMZİ YÜREĞİR Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "AKKAPI Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "ALİDEDE Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "AYDINLAR Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "BAHÇELİEVLER Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "BAHÇEŞEHİR Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "BARBAROS Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "BARIŞ Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "BEŞOCAK Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "BEY Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "BÜYÜKÇILDIRIM Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "BÜYÜKDİKİLİ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "CAMUZCU Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "CEMALPAŞA Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "ÇAPUTÇU Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "ÇINARLI Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "DAĞLIOĞLU Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "DEMETEVLER Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "DENİZLİ Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "DERVİŞLER Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "DÖRTAĞAÇ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "DÖŞEME Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "DUMLUPINAR Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "EMEK Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "FATİH Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "FEVZİPAŞA Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "GAZİPAŞA Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "GÖKÇELER Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "GÖLBAŞI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "GÜLBAHÇESİ Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "GÜLPINAR Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "GÜRSELPAŞA Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "HADIRLI Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "HANEDAN Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "HAVUZLUBAHÇE Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "HURMALI Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "HÜRRİYET Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "İSMETPAŞA Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "İSTİKLAL Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "KARAKUYU Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "KARASOKU Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "KARAYUSUFLU Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "KAVAKLI Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "KAYALIBAĞ Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "KAYIŞLI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "KOCAVEZİR Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "KOYUNCU Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "KOZA Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "KÖYLÜOĞLU Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "KURTULUŞ Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "KURUKÖPRÜ Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "KUYUMCULAR Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "KÜÇÜKÇILDIRIM Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "KÜÇÜKDİKİLİ Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "MEKAN Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "MESTANZADE Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "MEYDAN Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "MIDIK Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "MİRZAÇELEBİ Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "MİTHATPAŞA Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "MÜRSELOĞLU Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "NAMIK KEMAL Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "NARLICA Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "ONUR Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "OVA Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "PINAR Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "REŞATBEY Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "SAKARYA Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "SALMANBEYLİ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "SARIHAMZALI Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "SARIHUĞLAR Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "SARIYAKUP Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "SERİNEVLER Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "SÖĞÜTLÜ Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "SUCUZADE Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "SÜMER Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "ŞAKİRPAŞA Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "ŞEHİTDURAN Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "TELLİDERE Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "TEPEBAĞ Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "TÜRKOCAĞI Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "UÇAK Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "ULUCAMİİ Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "YALMANLI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "YENİ Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "YENİBARAJ Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "YENİBEY Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "YENİDAM Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "YEŞİLEVLER Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "YEŞİLOBA Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "YEŞİLYURT Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "YEŞİLYUVA Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "YOLGEÇEN Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "ZEYTİNLİ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "SEYHAN", "belediye": "SEYHAN", "mahalle": "ZİYAPAŞA Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "ADAPINAR Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "ADATEPE Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "AĞAÇLI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "AĞAÇPINAR Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "AKDAM Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "ALTIGÖZBEKİRLİ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "ALTIKARA Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "ALTIOCAK Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "ATATÜRK Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "AYDEMİROĞLU Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "AYDINLAR Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "AZİZLİ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "BAŞÖREN Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "BELEDİYE EVLERİ Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "BİRKENT Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "BOTA Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "BURHANİYE Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "BURHANLI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "BÜYÜKBURHANİYE Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "BÜYÜKKIRIM Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "BÜYÜKMANGIT Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "CAMUZAĞILI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "CEYHANBEKİRLİ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "CİVANTAYAK Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "CUMHURİYET Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "ÇAKALDERE Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "ÇATAKLI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "ÇATALHÜYÜK Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "ÇEVRETEPE Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "ÇİÇEKLİ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "ÇİFTLİKLER Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "ÇOKÇAPINAR Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "DAĞISTAN Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "DEĞİRMENDERE Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "DEĞİRMENLİ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "DİKİLİTAŞ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "DOKUZTEKNE Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "DORUK Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "DURHASANDEDE Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "DUTLUPINAR Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "EKİNYAZI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "ELMAGÖLÜ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "EMEK Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "ERENLER Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "ESENTEPE Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "FATİH SULTAN MEHMET Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "GAZİ OSMAN PAŞA Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "GÜMÜRDÜLÜ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "GÜNDOĞAN Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "GÜNLÜCE Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "HAMDİLLİ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "HAMİDİYE Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "HAMİTBEY Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "HAMİTBEYBUCAĞI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "HÜRRİYET Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "IRMAKLI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "ISIRGANLI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "İMRAN Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "İNCEYER Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "İNÖNÜ Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "İSALI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "İSTİKLAL Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "KARAKAYALI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "KELEMETİ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "KILIÇKAYA Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "KIVRIKLI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "KIZILDERE Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "KONAKOĞLU Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "KORUKLU Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "KÖPRÜLÜ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "KÖRKUYU Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "KÖSRELİ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "KURTKULAĞI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "KURTPINAR Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "KUZUCAK Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "KÜÇÜKBURHANİYE Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "KÜÇÜKKIRIM Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "KÜÇÜKMANGIT Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "MERCİMEK Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "MERCİN Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "MİTHAT PAŞA Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "MODERNEVLER Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "MURADİYE Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "MUSTAFABEYLİ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "NAMIK KEMAL Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "NARLIK Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "NAZIMBEY YENİKÖY Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "SAĞIRLAR Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "SAĞKAYA Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "SARIBAHÇE Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "SARIMAZI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "SARISAKAL Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "SELİMİYE Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "SİRKELİ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "SOĞUKPINAR Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "SOYSALLI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "ŞAHİN ÖZBİLEN Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "ŞEHİT HACI İBRAHİM Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "TATARLI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "TATLIKUYU Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "TOKTAMIŞ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "TUMLU Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "ULUS Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "ÜÇDUTYEŞİLOVA Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "VEYSİYE Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "YALAK Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "YARSUAT Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "YELLİBEL Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "YEŞİLBAHÇE Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "YEŞİLDAM Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "YILANKALE Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "CEYHAN", "belediye": "CEYHAN", "mahalle": "ZÜBEYDE HANIM Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "AKKAYA Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "AKOLUK Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "BAĞDATLI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "BAHÇECİK Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "BELENKÖY Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "ÇANDIRLAR Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "ÇONDU Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "ÇÜRÜKLER Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "DEĞİRMENCİUŞAĞI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "GAFFARUŞAĞI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "GEDİKLİ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "GÖBELLİ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "GÖKÇELİ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "GÜRÜMZE Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "GÜZPINARI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "HIDIRUŞAĞI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "İNCİRCİ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "İSLAM Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "KALEYÜZÜ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "KARACAOĞLAN Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "KARACAUŞAĞI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "KAŞALTI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "KAYADİBİ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "KAZANCI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "KEKLİKÇİ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "KIRIKUŞAĞI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "KISACIKLI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "KIZILYER Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "KOÇYAZI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "KONAKKURAN Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "KOVUKÇINAR Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "MANSURLU Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "MUSALAR Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "OLUCAK Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "ORMANCIK Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "ORTAKÖY Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "ORUÇLU Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "PAŞALI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "SÜLEMİŞLİ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "SÜPHANDERE Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "ŞAHMURATLI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "TENKERLİ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "TOKMANAKLI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "TORTULU Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "UĞURLUBAĞ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "YAYLAPINAR Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "YEREBAKAN Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "FEKE", "belediye": "FEKE", "mahalle": "YEŞİL DÜŞMÜŞ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "AKÇALI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "AKTAŞ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "ALTINOVA Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "AŞAĞIBELEMEDİK Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "AŞAĞIYÖRÜKLER Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "AYAKKIF Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "BARAKDAĞI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "BAŞKIF Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "BEKİRLİ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "BEYDEMİR Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "BOLACALI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "BUCAK Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "ÇAKALLI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "ÇATALAN Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "ÇECELİ Mah.", "durum": "Kırsal Alan Değil" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "ÇEVLİK Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "ÇOCUKLAR Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "ÇORLU Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "ÇUKUR Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "DEMİRÇİT Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "DÖŞEKEVİ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "DURAK Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "EĞLENCE Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "EMELCİK Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "ETEKLİ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "FETTAHLI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "FİLİKLİ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "GİLDİRLİ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "GÖKHASANLI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "GÜLÜŞLÜ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "GÜVENÇ Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "HACILI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "HACIMUSALI Mah.", "durum": "Kırsal Alan" },
  { "il": "ADANA", "ilce": "KARAİSALI", "belediye": "KARAİSALI", "mahalle": "KALEDAĞI Mah.", "durum": "Kırsal Alan" }
];
